# Generated by Django 6.1.1 on 2026-09-21 06:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('proposal_type', models.CharField(choices=[('DIRECT', 'Direct 2-Party Swap'), ('CYCLE_3', '3-Party Multi-Hop Cycle'), ('CYCLE_4', '4-Party Multi-Hop Cycle'), ('CYCLE_5', '5-Party Multi-Hop Cycle')], default='DIRECT', max_length=20)),
                ('status', models.CharField(choices=[('PENDING_ACCEPTANCE', 'Pending Participant Acceptance'), ('PARTIALLY_ACCEPTED', 'Partially Accepted'), ('READY_FOR_APPROVAL', 'All Accepted · Ready for Warden'), ('APPROVED', 'Warden Approved'), ('DECLINED', 'Declined by Participant'), ('EXPIRED', 'Proposal Expired'), ('COMPLETED', 'Occupancy Transferred'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_ACCEPTANCE', max_length=25)),
                ('compatibility_score', models.FloatField(default=100.0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('entity_type', models.CharField(db_index=True, max_length=50)),
                ('entity_id', models.CharField(max_length=50)),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_approvals', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='exchange.exchangeproposal')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_room_type', models.CharField(blank=True, choices=[('SINGLE', 'Single Occupancy'), ('DOUBLE', 'Double Sharing'), ('TRIPLE', 'Triple Sharing'), ('FOUR_SHARING', 'Four Sharing')], max_length=20)),
                ('preferred_floor', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Academic, medical, or study preference explanation')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active & Searching'), ('MATCHED', 'Match Found'), ('PROPOSED', 'In Proposal Cycle'), ('COMPLETED', 'Transfer Completed'), ('WITHDRAWN', 'Withdrawn by Student'), ('EXPIRED', 'Expired'), ('REJECTED', 'Eligibility Rejected')], db_index=True, default='ACTIVE', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_exchange_requests', to='hostel.bed')),
                ('preferred_hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_requests', to='hostel.hostel')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to=settings.AUTH_USER_MODEL)),
                ('specific_target_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directly_requested_in', to='hostel.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('PROPOSAL_RECEIVED', 'Exchange Proposal Received'), ('PARTICIPANT_ACCEPTED', 'Participant Accepted'), ('PARTICIPANT_DECLINED', 'Participant Declined'), ('READY_FOR_APPROVAL', 'Proposal Ready for Warden Approval'), ('TRANSFER_COMPLETED', 'Transfer Completed Successfully'), ('PROPOSAL_EXPIRED', 'Proposal Expired'), ('GENERAL_ALERT', 'General Alert')], default='GENERAL_ALERT', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('COOLING_OFF_DAYS', 'Cooling-Off Period (Days)'), ('MAX_CHAIN_LENGTH', 'Maximum Cycle Chain Length'), ('PROPOSAL_VALIDITY_HOURS', 'Proposal Validity (Hours)'), ('FEE_CLEARANCE_REQUIRED', 'Mandatory Fee Clearance'), ('DISCIPLINARY_CHECK', 'Strict Disciplinary Hold Check'), ('GENDER_STRICT_SEPARATION', 'Strict Gender Residence Policy')], max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('int_value', models.IntegerField(default=0, help_text='Numeric parameter e.g. 30 days or 5 chain length')),
                ('bool_value', models.BooleanField(default=True, help_text='Boolean policy flag')),
                ('description', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_policies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_code', models.CharField(db_index=True, max_length=35, unique=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_transfers', to=settings.AUTH_USER_MODEL)),
                ('new_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferred_to_records', to='hostel.bed')),
                ('previous_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferred_from_records', to='hostel.bed')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_records', to='exchange.exchangeproposal')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completed_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('PENDING', 'Pending Decision'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=15)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('current_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_departures', to='hostel.bed')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='exchange.exchangeproposal')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='exchange.exchangerequest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_participations', to=settings.AUTH_USER_MODEL)),
                ('target_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_destinations', to='hostel.bed')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('proposal', 'student')},
            },
        ),
    ]
