# Generated by Django 6.1.1 on 2026-09-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerequest',
            name='preferred_room_type',
            field=models.CharField(blank=True, choices=[('SINGLE', '1-Seater (Single)'), ('DOUBLE', '2-Seater (Double Sharing)'), ('TRIPLE', '3-Seater (Triple Sharing)'), ('FOUR_SHARING', '4-Seater (Quad Sharing)'), ('SEVEN_SEATER', '7-Seater (Dormitory)'), ('EIGHT_SEATER', '8-Seater (Dormitory)')], max_length=20),
        ),
    ]
